# fly.toml app configuration file generated for kimmotech-nextjs on 2025-06-01T14:58:00+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kimmotech-nextjs'
primary_region = 'jnb'

[build.args]
  NEXT_PUBLIC_PYTHON_BACKEND_URL = "https://kimmotech-python-solitary-morning-2567.fly.dev"
  NEXT_PUBLIC_GTM_ID = "GTM-TKKJB2MQ"
  NEXT_PUBLIC_GA_ID = "G-WDH1M0TF3N"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  PORT = "3000"
  NEXT_PUBLIC_GTM_ID = "GTM-TKKJB2MQ"
  NEXT_PUBLIC_GA_ID = "G-WDH1M0TF3N"
  NEXT_PUBLIC_PYTHON_BACKEND_URL = "https://kimmotech-python-solitary-morning-2567.fly.dev"